project:
  type: book
  output-dir: docs

book:
  title: "Introdução ao Direito Ambiental"
  author: "Lucas S.B. Jordão"
  date: "23/03/2025"
  chapters:
    - index.qmd
    - introducao.qmd
    - ordenamento-juridico.qmd
    - constituicao.qmd
    - direito-ambiental.qmd
    - pnma.qmd
    - cdb.qmd
    # - ods.qmd
    - references.qmd
  google-analytics: "G-HMN3YR5PSN"

bibliography: references.bib

format:
  html:
    smooth-scroll: true
    theme:
      light: brite
      dark: cyborg
    number-depth: 3
    number-sections: false
    css: "style.css"
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>
          <link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" rel="stylesheet">
    include-after-body: 
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
          <script>
            AOS.init();
          </script>
lang: pt

comments:
  hypothesis: 
    theme: clean
  giscus: 
    repo: lsbjordao/Introducao-Direito-Ambiental

