# Direito Ambiental Constitucional

- O art. 225 da CF/88 é a norma-matriz do Direito Ambiental brasileiro. É a norma reveladora do **direito de todos ao Meio Ambiente Ecologicamente Equilibrado** (MAEE). 

::: {.callout-tip collapse="true"}

## O princípio da proibição de retrocesso ambiental

Embora o art. 225 não esteja explicitamente listado entre as cláusulas pétreas no art. 60, § 4º, da CF/88, muitos juristas argumentam que o direito ao MAEE possui *status* de cláusula pétrea por estar intrinsecamente ligado aos direitos e garantias individuais, que são protegidos contra emendas tendentes à sua abolição.

Essa interpretação se baseia na compreensão de que os direitos ambientais são fundamentais para a dignidade humana e, portanto, estão abrangidos pela proteção conferida às cláusulas pétreas. Assim, qualquer proposta de emenda que vise abolir ou reduzir a proteção ao meio ambiente poderia ser considerada inconstitucional por violar essa proteção implícita.

Apesar de não estar expressamente designado como cláusula pétrea, o art. 225 é amplamente reconhecido como portador de um direito fundamental que goza de proteção constitucional reforçada, **impedindo retrocessos legislativos** que comprometam a integridade do MAEE [@Senado2011].

:::

## Norma-matriz

::: {.callout-note icon=false}

## CF/88, art. 225

**Todos** têm **direito ao meio ambiente ecologicamente equilibrado**, **bem de uso comum do povo** e **essencial à sadia qualidade de vida**, impondo-se ao Poder Público e à coletividade o dever de defendê-lo e preservá-lo para as presentes e futuras gerações:

:::

- **Todos**: 
  - Refere-se a pessoas naturais, sejam brasileiros ou estrangeiros, e jurídicas. O uso desse termo abrangente estabelece um compromisso global e um pacto intergeracional.

- **direito ao MAEE**: 
  - O MAEE refere-se à [boa] qualidade do meio ambiente; um meio ambiente de boa qualidade é ecologicamente equilibrado. Com efeito, diz-se que cabe ao poder público o controle da qualidade ambiental, o estabelecimento de critérios e padrões da qualidade ambiental; para garantir a proteção do MAEE;
  - O direito à integridade do meio ambiente é um típico direito de terceira geração.

::: {.callout-tip collapse="true" style="margin-left: 60px;"}

As gerações do direito estão relacionadas aos três princípios da Revolução Francesa:

1. Direitos civis e políticos (liberdade)

2. Direitos sociais e coletivos (igualdade)

3. Direitos transindividuais (fraternidade)

:::

- **bem de uso comum do povo**: 
  - O meio ambiente como um todo é considerado um bem público imaterial, que se convencionou classificá-lo como um macrobem. Por sua vez, os microbens são bens materiais; é todo e qualquer elemento constituinte e integrante do meio ambiente [@Benjamin1993];
  - O meio ambiente, enquanto um macrobem, e o próprio direito de fruição a um MAEE são considerados **inalienáveis** e **indisponíveis**. 
  - Segundo o art. 99 do Código Civil (Lei nº 10.406/02.), os bens de uso comum são <mark>inalienáveis</mark>, tais como rios, mares, estradas, ruas e praças. Os bens de uso comum do povo também são considerados <mark>indisponíveis</mark>, ou seja, não são susceptíveis de apropriação privada mesmo quando seus elementos constitutivos pertençam a particulares. Significa que ninguém pode dispor da qualidade do meio ambiente conforme sua vontade, porque ela não integra a sua disponibilidade [@Silva2019];
  - O meio ambiente enquanto macrobem é um <mark>bem de interesse difuso</mark>, pertencente a toda coletividade. Os interesses ou direitos difusos são transindividuais, indivisíveis, e a titularidade é exercida por pessoas indeterminadas e ligadas por circunstâncias de fato, conforme disposto no art. 81 do Código de Defesa do Consumidor (Lei Federal nº 8.708/1990) [@Mesquita2012].

::: {.callout-note icon=false collapse="true" style="margin-left: 60px;"}

## Lei Federal nº 8.078/1990, art. 81

Art. 81. A defesa dos interesses e direitos dos consumidores e das vítimas poderá ser exercida em juízo individualmente, ou a título coletivo.

<span style="display: block; margin-left: 30px;">
  Parágrafo único. A defesa coletiva será exercida quando se tratar de:<br>

  <span style="display: block; margin-left: 60px;">
    I - <mark>interesses ou direitos difusos</mark>, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível, de que sejam titulares pessoas indeterminadas e ligadas por circunstâncias de fato;<br>
    II - interesses ou direitos coletivos, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível de que seja titular grupo, categoria ou classe de pessoas ligadas entre si ou com a parte contrária por uma relação jurídica base;<br>
    III - interesses ou direitos individuais homogêneos, assim entendidos os decorrentes de origem comum.
  </span>
</span>

:::

- **essencial à sadia qualidade de vida**: 
  - A manutenção do MAEE é fundamental para o bem-estar e sadia qualidade de vida. Em outras palavras, a sadia qualidade de vida é a finalidade última da proteção ao MAEE. A análise lógica do texto do art. 225 permite a interpretação de que o MAEE é essencial para a sadia qualidade da vida humana.

## Instrumentos para a garantia da efetividade do direito ao MAEE

A proteção do MAEE, essencial para a sadia qualidade de vida, para a garantia do desenvolvimento nacional  e para  a construção de uma sociedade justa socialmente e solidária, está diretamente relacionada à conservação da biodiversidade e ao combate ao declínio e à extinção das espécies.

O § 1º do art. 225 estatui os instrumentos para a garantia da efetividade do direito ao MAEE [@Silva2019].

::: {.callout-note icon=false}

## CF/88, art. 225, § 1º

Para assegurar a efetividade desse direito, incumbe ao Poder Público:

<span style="display: block; margin-left: 30px;">
<table class="table table-hover">
  <tbody>
    <tr>
      <td>I</td>
      <td>Preservar e restaurar os processos ecológicos essenciais e prover o manejo ecológico das espécies e ecossistemas;</td>
    </tr>
    <tr>
      <td>II</td>
      <td>Preservar a diversidade e a integridade do patrimônio genético do País e fiscalizar as entidades dedicadas à pesquisa e manipulação de material genético;</td>
    </tr>
    <tr>
      <td>III</td>
      <td>Definir, em todas as unidades da Federação, espaços territoriais e seus componentes a serem especialmente protegidos, sendo a alteração e a supressão permitidas somente através de lei, vedada qualquer utilização que comprometa a integridade dos atributos que justifiquem sua proteção;</td>
    </tr>
    <tr>
      <td>IV</td>
      <td>Exigir, na forma da lei, para instalação de obra ou atividade potencialmente causadora de significativa degradação do meio ambiente, estudo prévio de impacto ambiental, a que se dará publicidade;</td>
    </tr>
    <tr>
      <td>V</td>
      <td>Controlar a produção, a comercialização e o emprego de técnicas, métodos e substâncias que comportem risco para a vida, a qualidade de vida e o meio ambiente;</td>
    </tr>
    <tr>
      <td>VI</td>
      <td>Promover a <a title="Política Nacional de Educação Ambiental (Lei Federal nº 9.795/1999)" href="https://www.planalto.gov.br/ccivil_03/leis/l9795.htm">educação ambiental</a> em todos os níveis de ensino e a conscientização pública para a preservação do meio ambiente;</td>
    </tr>
    <tr>
      <td>VII</td>
      <td>Proteger a fauna e a flora, vedadas, na forma da lei, as práticas que coloquem em risco sua função ecológica, provoquem a extinção de espécies ou submetam os animais a crueldade;</td>
    </tr>
    <tr>
      <td>VIII</td>
      <td>Manter regime fiscal favorecido para os biocombustíveis e para o hidrogênio de baixa emissão de carbono, na forma de lei complementar, a fim de assegurar-lhes tributação inferior à incidente sobre os combustíveis fósseis, capaz de garantir diferencial competitivo em relação a estes, especialmente em relação às contribuições de que tratam o art. 195, I, "b", IV e V, e o art. 239 e aos impostos a que se referem os arts. 155, II, e 156-A.</td>
    </tr>
  </tbody>
</table>
</span>

:::

## Outras determinações do art. 225

::: {.callout-note icon=false}

## CF/88, art. 225, § 2º

Aquele que explorar recursos minerais fica obrigado a recuperar o meio ambiente degradado, de acordo com solução técnica exigida pelo órgão público competente, na forma da lei.

:::

::: {.callout-note icon=false}

## CF/88, art. 225, § 3º

As condutas e atividades consideradas lesivas ao meio ambiente sujeitarão os infratores, pessoas físicas ou jurídicas, a sanções penais e administrativas, independentemente da obrigação de reparar os danos causados.

:::

::: {.callout-note icon=false}

## CF/88, art. 225, § 4º

A Floresta Amazônica brasileira, a Mata Atlântica, a Serra do Mar, o Pantanal Mato-Grossense e a Zona Costeira são patrimônio nacional, e sua utilização far-se-á, na forma da lei, dentro de condições que assegurem a preservação do meio ambiente, inclusive quanto ao uso dos recursos naturais.

:::

::: {.callout-note icon=false}

## CF/88, art. 225, § 5º

São indisponíveis as terras devolutas ou arrecadadas pelos Estados, por ações discriminatórias, necessárias à proteção dos ecossistemas naturais.

:::

::: {.callout-note icon=false}

## CF/88, art. 225, § 6º

As usinas que operem com reator nuclear deverão ter sua localização definida em lei federal, sem o que não poderão ser instaladas.

:::

::: {.callout-note icon=false}

## CF/88, art. 225, § 6º

Para fins do disposto na parte final do inciso VII do § 1º deste artigo, não se consideram cruéis as práticas desportivas que utilizem animais, desde que sejam manifestações culturais, conforme o § 1º do art. 215 desta Constituição Federal, registradas como bem de natureza imaterial integrante do patrimônio cultural brasileiro, devendo ser regulamentadas por lei específica que assegure o bem-estar dos animais envolvidos.

:::

## Repartição das competências comuns

A repartição das competências comuns prevista no artigo 23 da Constituição Federal de 1988 é considerada uma norma constitucional de eficácia limitada, pois sua plena aplicabilidade dependia da edição de uma lei complementar que regulamentasse a cooperação entre os entes federativos. Essa regulamentação foi estabelecida pela [Lei Complementar nº 140/2011](https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp140.htm), que fixou normas para a cooperação entre a União, os Estados, o Distrito Federal e os Municípios, visando ao equilíbrio do desenvolvimento e do bem-estar em âmbito nacional.

A LC 140/2011 detalha as atribuições administrativas de cada ente federativo em matéria ambiental, promovendo um modelo de federalismo cooperativo. Ela estabelece, por exemplo, as competências específicas para o licenciamento ambiental e a fiscalização, buscando evitar sobreposições e conflitos entre os entes federativos.

### Aplicabilidade das normas constitucionais

As normas constitucionais possuem diferentes graus de aplicabilidade e eficácia, sendo classificadas em três categorias principais:

- eficácia **plena**
  - As normas constitucionais de **eficácia plena** são as que podem ser aplicadas de imediato, como a instituição da língua portuguesa como idioma oficial (CF/88, art. 13).
- eficácia **contida**
  - As normas constitucionais de **eficácia contida** também têm aplicabilidade imediata, mas seu alcance pode ser restringido pela lei ordinária, como no art. 5º, XIII: 
  
  > é livre o exercício de qualquer trabalho, ofício ou profissão, atendidas as qualificações profissionais que a lei estabelecer.
- eficácia **limitada**
  - As normas constitucionais de **eficácia limitada** são as que dependem de complementação de outras normas para serem aplicadas, **como no parágrafo único do art. 23 da CF/88**, que define **normas sobre a competência comum** da União, dos Estados, do Distrito Federal e dos Municípios: 

  > Leis complementares fixarão normas para a cooperação entre a União e os Estados, o Distrito Federal e os Municípios, tendo em vista o equilíbrio do desenvolvimento e do bem-estar em âmbito nacional.

### Lei Complementar nº 140/11

::: {.callout-note icon=false}

## LC 140/11

Art. 1º Esta Lei Complementar fixa normas, nos termos dos incisos III, VI e VII do caput e do parágrafo único do **art. 23 da Constituição Federal**, para a **cooperação** entre a União, os Estados, o Distrito Federal e os Municípios nas ações administrativas decorrentes do **exercício da competência comum** relativas à proteção das paisagens naturais notáveis, à proteção do meio ambiente, ao combate à poluição em qualquer de suas formas e à preservação das florestas, da fauna e da flora.

:::

---

**Questões:**

<iframe 
  src="https://docs.google.com/forms/d/e/1FAIpQLScPZuJv7Ui5lYtTy-MmqlXBDt1Z-XTbW3u_aWhp7FHAbXdvtQ/viewform?embedded=true" 
  width="100%" 
  height="1500" 
  frameborder="0" 
  marginheight="0" 
  marginwidth="0">
  Carregando…
</iframe>