# Política Nacional do Meio Ambiente

## Lei Federal nº 9.638/1981

A Política Nacional do Meio Ambiente (PNMA) é estabelecida pela Lei Federal nº 9.638/1981.

## Estabelecimento da PNMA e criação do SISNAMA

::: {.callout-note icon=false}

## PNMA, art. 1º

Esta lei, com fundamento nos incisos VI e VII do art. 23 e no art. 235 da Constituição, estabelece a Política Nacional do Meio Ambiente, seus fins e mecanismos de formulação e aplicação, constitui o Sistema Nacional do Meio Ambiente (Sisnama) e institui o Cadastro de Defesa Ambiental.

:::

O SISNAMA é composto pelo:

- ÓRGÃO SUPERIOR: Conselho de Governo, com a função de assessorar o Presidente da República;
- ÓRGÃO CENTRAL: Ministério do Meio Ambiente (MMA);
- ÓRGÃO CONSULTIVO E DELIBERATIVO: Conselho Nacional do Meio Ambiente (CONAMA);
- ÓRGÃOS EXECUTORES: Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis (IBAMA) e Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio).

## Conceitos importantes

A PNMA é inovadora ao definir **meio ambiente**, **recursos ambientais**, **degradação ambiental**, **poluição** e **poluidor**.

### Meio ambiente

::: {.callout-note icon=false}

## PNMA, art. 3º, I

**meio ambiente**, o conjunto de condições, leis, influências e interações de ordem física, química e biológica, que permite, abriga e rege a vida em todas as suas formas.

:::

### Recursos ambientais

::: {.callout-note icon=false}

## PNMA, art. 3º, V

**recursos ambientais**: a atmosfera, as águas interiores, superficiais e subterrâneas, os estuários, o mar territorial, o solo, o subsolo, os elementos da biosfera, a fauna e a flora. 

:::

### Degradação ambiental

::: {.callout-note icon=false}

## PNMA, art. 3º, II

**degradação da qualidade ambiental**, a alteração adversa das características do meio ambiente;

:::

### Poluição

::: {.callout-note icon=false}

## PNMA, art. 3º, III

**poluição**, a degradação da qualidade ambiental resultante de atividades que direta ou indiretamente:

<span style="display: block; margin-left: 30px;">
    a) prejudiquem a saúde, a segurança e o bem-estar da população;<br>
    b) criem condições adversas às atividades sociais e econômicas;<br>
    c) afetem desfavoravelmente a biota;<br>
    d) afetem as condições estéticas ou sanitárias do meio ambiente;<br>
    e) lancem matérias ou energia em desacordo com os padrões ambientais estabelecidos;
</span>

:::

### Poluidor

::: {.callout-note icon=false}

## PNMA, art. 3º, IV

**poluidor**, a pessoa física ou jurídica, de direito público ou privado, responsável, direta ou indiretamente, por atividade causadora de degradação ambiental;

:::